### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by cdavietei** [skandasoft/open-in-browsers#11]
[Enter steps to reproduce below:]
1. Select Packages > open-in-browsers > Toggle
2. Error

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package, v0.0.11
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/Chris/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:64

TypeError: Cannot read property 'getPath' of undefined
    at OpenInBrowsersView.getFilePath (/Users/Chris/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:64:21)
    at OpenInBrowsersView.open (/Users/Chris/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:84:14)
    at OpenInBrowsersView.openBrowser (/Users/Chris/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:52:8)
    at atom-workspace.subscriptions.add.atom.commands.add.open-in-browsers:toggle (/Users/Chris/.atom/packages/open-in-browsers/lib/open-in-browsers.coffee:135:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -1:20.1.0 tree-view:add-file (span.name.icon.icon-repo)
  2x -1:15.2.0 application:add-project-folder (span.name.icon.icon-repo)
     -0:01.0 open-in-browsers:toggle (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false
  }
}
```
### Installed Packages

``` coffee
# User
docblockr, v0.7.3
open-in-browsers, v0.0.11
refactor, v0.6.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
Can you check the latest patch.
