### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mainModule' of undefined

### ISSUE THREAD

**Issue by Randagio13** [skandasoft/open-in-browsers#13]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package, v0.0.13
### Stack Trace

Uncaught TypeError: Cannot read property 'mainModule' of undefined

```
At /Users/alessandrocasazza13/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:80

TypeError: Cannot read property 'mainModule' of undefined
    at OpenInBrowsersView.open (/Users/alessandrocasazza13/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:80:9)
    at OpenInBrowsersView.openBrowser (/Users/alessandrocasazza13/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:51:8)
    at atom-workspace.<anonymous> (/Users/alessandrocasazza13/.atom/packages/open-in-browsers/lib/open-in-browsers.coffee:138:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```
### Commands

```
  3x -3:50.8.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:50.2.0 core:select-left (atom-text-editor.editor.is-focused)
     -3:49.2.0 core:paste (atom-text-editor.editor.is-focused)
 16x -3:48.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:46.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -3:46.2.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -3:45.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:45.4.0 core:select-left (atom-text-editor.editor.is-focused)
     -3:43.3.0 core:paste (atom-text-editor.editor.is-focused)
     -3:41.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:56.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -2:52.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:44.8.0 open-in-browsers:Chrome (span.name.icon.icon-file-text)
     -0:57.7.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:24 open-in-browsers:toggle (atom-text-editor.editor.is-focused)
     -0:01.0 open-in-browsers:BrowserPlus (span.name.icon.icon-file-text)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-material-ui",
      "babel-react-syntax"
    ]
  },
  "open-in-browsers": {}
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v1.2.10
auto-indent, v0.5.0
autocomplete-ctags, v0.4.1
autocomplete-modules, v1.4.1
babel-react-syntax, v1.1.0
file-icons, v1.7.4
git-diff-details, v1.2.0
highlight-selected, v0.11.2
hyperclick, v0.0.35
js-hyperclick, v1.4.2
language-SCSS, v0.4.0
language-babel, v2.17.3
linter, v1.11.4
linter-eslint, v7.2.0
linter-scss-lint, v2.5.1
merge-conflicts, v1.4.1
minimap, v4.22.1
open-in-browsers, v0.0.13
pretty-json, v1.0.3
react-snippets, v0.4.2
rest-client, v1.0.0
terminal-plus, v0.14.5
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
check the latest patch
