### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by onurclk** [skandasoft/open-in-browsers#21]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package, v0.0.16
### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/onurcolak/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:855

RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at Sizzle (/Users/onurcolak/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:855:26)
    at Function.Sizzle.matches (/Users/onurcolak/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:1396:9)
    at Function.jQuery.filter (/Users/onurcolak/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:2672:15)
    at OpenInBrowsersView.jQuery.fn.(anonymous function) [as children] (/Users/onurcolak/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3010:21)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:52:6)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at OpenInBrowsersView.open (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:87:8)
    at OpenInBrowsersView.openBrowser (/Users/onurcolak/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
```
### Commands

```
     -4:24 tabs:close-all-tabs (atom-text-editor.editor.is-focused)
     -4:16.4.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -4:12.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:57.4.0 atom-live-server:start-3000 (atom-text-editor.editor.is-focused)
  2x -2:26.9.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:28.7.0 atom-live-server:start-3000 (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "open-in-browsers": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.4
atom-live-server, v1.2.5
open-in-browsers, v0.0.16

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can you update to the latest version

**Comment by YourGrace08** [comment]
i really need to test the site I am working on what is going on with this packadge
