### ISSUE TITLE
Uncaught Error: Cannot find module '../project'

### ISSUE THREAD

**Issue by johnnyweb1** [skandasoft/open-in-browsers#23]
[Enter steps to reproduce below:]
1. Select any of the installed Browsers
2. Errors out.
3. Happens on all browsers regardless if they are are active or not. (tested on IE, Chrome, Safari)

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package, v0.0.17
### Stack Trace

Uncaught Error: Cannot find module '../project'

```
At module.js:340

Error: Cannot find module '../project'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Function.OpenInBrowsersView.getFilePath (/Users/john/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:107:15)
    at OpenInBrowsersView.getFilePath (/Users/john/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:71:24)
    at OpenInBrowsersView.open (/Users/john/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:83:14)
    at OpenInBrowsersView.openBrowser (/Users/john/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at HTMLSpanElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLSpanElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -9:47.5.0 window:save-all (atom-text-editor.editor.is-focused)
     -9:06.0 open-in-browsers:Chrome (span.name.icon.icon-file-text)
     -9:00.5.0 open-in-browser:open-tree-view (span.name.icon.icon-file-text)
     -6:41.7.0 core:paste (atom-text-editor.editor.is-focused)
  2x -6:38.8.0 window:save-all (atom-text-editor.editor.is-focused)
     -6:16.6.0 open-in-browser:open-tree-view (span.name.icon.icon-file-text)
     -4:45.8.0 core:paste (atom-text-editor.editor.is-focused)
     -4:42.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:39.1.0 window:save-all (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.23.0
emmet, v2.4.3
highlight-selected, v0.11.2
minimap, v4.24.6
minimap-pigments, v0.2.1
monokai-seti, v0.7.0
open-in-browser, v0.4.7
open-in-browsers, v0.0.17
pigments, v0.30.0

# Dev
No dev packages
```

**Comment by johnnyweb1** [comment]
Resolved thank you.
