### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by magicdrums** [skandasoft/open-in-browsers#24]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Fedora release
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package, v0.0.19
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /home/16422152/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:102

TypeError: Cannot read property 'replace' of undefined
    at Function.OpenInBrowsersView.getFilePath (/home/16422152/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:102:18)
    at OpenInBrowsersView.getFilePath (/home/16422152/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:71:24)
    at OpenInBrowsersView.open (/home/16422152/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:83:14)
    at OpenInBrowsersView.openBrowser (/home/16422152/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at atom-workspace.subscriptions.add.atom.commands.add.open-in-browsers:toggle (/home/16422152/.atom/packages/open-in-browsers/lib/open-in-browsers.coffee:194:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -2:22 core:paste (atom-text-editor.editor.is-focused)
     -1:59.6.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -1:49.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 open-in-browsers:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atomic-chrome, v0.3.0
open-in-browsers, v0.0.19
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by guchenghao** [comment]
the same problem in atom v1.9.2

**Comment by skandasoft** [comment]
you need to have browser-plus installed

**Comment by Cryptina** [comment]
and v1.11.2

**Comment by skandasoft** [comment]
can you check the updated package ..and if problem still exist can you detail the method to open the file in browser
