### ISSUE TITLE
#open in browser not opening

### ISSUE THREAD

**Issue by Tikam02** [skandasoft/open-in-browsers#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package, v0.0.19

### Stack Trace

Uncaught TypeError: Cannot read property 'mainModule' of undefined

```
At /F:/IDE/AtomPortable/Data/atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:139

TypeError: Cannot read property 'mainModule' of undefined
    at OpenInBrowsersView.open (file:///F:/IDE/AtomPortable/Data/atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:78:9)
    at OpenInBrowsersView.openBrowser (file:///F:/IDE/AtomPortable/Data/atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at atom-workspace.<anonymous> (file:///F:/IDE/AtomPortable/Data/atom/packages/open-in-browsers/lib/open-in-browsers.coffee:200:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (F:\IDE\AtomPortable\App\Atom\resources\app.asar\src\command-registry.js:260:29)
    at F:\IDE\AtomPortable\App\Atom\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (F:\IDE\AtomPortable\App\Atom\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (F:\IDE\AtomPortable\App\Atom\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-li.<anonymous> (F:\IDE\AtomPortable\App\Atom\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (F:\IDE\AtomPortable\App\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (F:\IDE\AtomPortable\App\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
  4x -5:29.8.0 autoflow:reflow-selection (atom-text-editor.editor.is-focused)
  7x -5:28.3.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -5:27.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:19 open-in-browser:open (atom-text-editor.editor)
     -5:01.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:59.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -2:45 intentions:highlight (atom-text-editor.editor.is-focused)
     -2:42.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:41.9.0 intentions:highlight (atom-text-editor.editor.is-focused)
  2x -2:41.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:23.9.0 open-in-browsers:BrowserPlus (ul.list-inline.tab-bar.inset-panel)
     -2:01.0 command-palette:toggle (a.btn-copy-report.icon.icon-clippy)
     -1:54.8.0 open-in-browsers:addBrowser (a.btn-copy-report.icon.icon-clippy)
     -0:20 intentions:highlight (atom-text-editor.editor.is-focused)
     -0:19.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:06.2.0 open-in-browsers:BrowserPlus (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "angularjs-helper",
      "atom-clock"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "nord-atom-ui",
      "monokai-seti"
    ]
  },
  "open-in-browsers": {
    "LocalHost": true
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v1.2.0 (inactive)
achievements, v0.9.0 (active)
advanced-open-file, v0.16.4 (inactive)
aligner-css, v1.2.0 (active)
aligner-javascript, v1.0.0 (active)
angular-2-typeScript-snippets, v0.6.3 (active)
angular-bootstrap, v1.0.1 (inactive)
angular2-snippets, v0.3.0 (active)
angular2-snippets-atom, v0.7.0 (active)
angularjs, v0.3.5 (active)
angularjs-boilerplate-snippets, v0.3.1 (active)
angularjs-helper, v0.10.2 (inactive)
angularjs-snippets, v0.10.18 (active)
angularjs-styleguide-snippets, v0.9.1 (active)
atom-angular-material-snippets, v1.3.0 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-bemmet, v2.0.0 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-bootstrap4, v1.4.0 (active)
atom-bugs, v0.19.9 (active)
atom-cerebral-signal-bootstrap, v1.3.0 (inactive)
atom-clock, v0.0.8 (inactive)
atom-css-class-checker, v0.4.3 (inactive)
atom-css-comb, v3.1.0 (inactive)
atom-darcula, v0.2.0 (inactive)
atom-html-preview, v0.1.22 (active)
atom-htmltidy, v5.1.0 (active)
atom-javascript-console-snippets, v0.10.0 (active)
atom-jshint, v2.0.0 (active)
atom-jshinter, v0.1.3 (active)
atom-json-color, v0.4.2 (active)
atom-live-server, v1.2.5 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.8 (inactive)
atom-monokai, v0.10.4 (inactive)
atom-ng-attr-hint, v2.1.0 (inactive)
atom-nodejs-snippets, v1.3.2 (inactive)
atom-prettify, v0.1.3 (inactive)
atom-react-native-css, v1.1.3 (active)
atom-terminal, v0.8.0 (inactive)
atom-ternjs, v0.16.1 (inactive)
atom-visual-studio-code-ui, v1.3.4 (inactive)
atomic-ui, v1.5.2 (inactive)
auto-detect-indentation, v1.3.0 (active)
auto-indent, v0.5.0 (active)
auto-indent-file, v0.2.0 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-angular-material, v0.4.0 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-python, v1.8.20 (active)
bootstrap-3-snippetset, v0.0.6 (active)
bootstrap-sass-snippets, v0.1.0 (active)
bootstrap3-plus, v0.1.2 (inactive)
bootstrap3-snippets, v0.1.2 (active)
bootstrap4-snippets, v0.2.2 (active)
bug-report, v0.7.1 (active)
bugzilla-number, v0.1.0 (active)
busy-signal, v1.2.0 (active)
chrome-color-picker, v0.8.0 (inactive)
clock, v1.7.2 (active)
color-picker, v2.2.3 (active)
colorful-json, v1.0.0 (active)
cordova-snippets, v0.1.0 (active)
css-clean, v2.15.0 (inactive)
css-color-underline, v1.0.1 (active)
css-comb, v2.5.0 (active)
css-snippets, v1.1.0 (active)
css-spy, v0.6.0 (active)
csscomb, v0.3.1 (inactive)
darcula-syntax, v0.1.2 (inactive)
dark-flat-ui, v1.2.4 (inactive)
darkula-ui, v0.1.0 (inactive)
debug, v0.0.1 (active)
debugger, v0.0.1 (active)
dracula-theme, v1.2.8 (inactive)
dracula-ui, v0.3.0 (inactive)
emmet, v2.4.3 (active)
emmet-jsx-css-modules, v1.0.0 (active)
emmet-jsx-props, v1.2.5 (active)
emmet-simplified, v2.5.0 (active)
emmet-snippets-compatibility, v1.0.6 (active)
emmet-snippets-compatibility-but-less-extreme, v1.1.0 (active)
es6-javascript, v1.0.0 (inactive)
eval-javascript, v1.2.0 (inactive)
file-type-icons, v1.3.3 (active)
file-types, v0.5.4-p1 (active)
gdb-debug, v0.0.3 (active)
genesis-snippets, v2.1.0 (inactive)
git-checkout, v0.3.2 (active)
git-commit, v1.5.3 (active)
git-plus, v5.29.0 (active)
git-status, v0.3.4 (inactive)
git-tools, v0.4.1 (inactive)
go-config, v1.2.4 (active)
go-debug, v0.1.22 (active)
go-get, v2.1.1 (active)
html-id-class-snippets, v1.4.1 (active)
html-nested-comments, v3.2.1 (inactive)
html-to-css, v0.2.2 (inactive)
htmlhint, v1.1.4 (active)
hydra-syntax-theme, v2.0.3 (inactive)
intentions, v1.1.2 (active)
jade-beautify, v0.1.5 (inactive)
jade-bootstrap3-snippets, v0.3.0 (active)
javascript-object-snippets, v0.3.0 (active)
javascript-snippets, v1.2.1 (active)
javascript-standard-snippets, v0.2.1 (active)
jscs-fixer, v1.3.0 (inactive)
jshint, v1.8.6 (active)
jshint-snippets, v0.2.2 (active)
json-colorer, v0.3.0 (active)
language-javascript-better, v1.7.1 (active)
language-javascript-jsx, v0.3.7 (active)
language-typescript-grammars-only, v1.5.0 (active)
linter, v1.11.18 (active)
linter-bootlint, v1.0.2 (active)
linter-docker, v0.1.4 (active)
linter-htmlhint, v1.3.1 (active)
linter-jscs, v4.1.0 (inactive)
linter-jshint, v3.0.1 (active)
linter-pep8, v1.3.2 (active)
linter-sass-lint, v1.7.4 (active)
linter-scss-lint, v3.0.4 (active)
linter-spell, v0.12.6 (active)
linter-spell-javascript, v0.7.1 (active)
linter-write-good, v0.8.0 (active)
livestyle-atom, v0.2.7 (active)
logo-file-icons, v1.3.0 (active)
material, v2.2.0 (inactive)
meteor-assist, v0.3.0 (inactive)
minimap, v4.26.4 (active)
minimap-pigments, v0.2.2 (active)
Monokai-Black-and-White, v0.3.0 (inactive)
monokai-seti, v0.7.0 (active)
node-debugger, v1.9.1 (active)
node-on-fire, v0.1.0 (active)
node-requirer, v0.1.12 (inactive)
nodejs-snippets, v2.0.2 (active)
nord-atom-syntax, v0.4.0 (inactive)
nord-atom-ui, v0.9.0 (active)
open-git-modified-files, v0.2.4 (inactive)
open-in-browser, v0.4.7 (active)
open-in-browsers, v0.0.19 (active)
open-recent, v5.0.0 (active)
pigments, v0.37.0 (active)
Quick-JavaScript, v2.2.0 (active)
sass-comment, v1.4.0 (active)
sass-compiler, v0.4.0 (active)
seti-syntax, v1.0.1 (inactive)
standardjs-snippets, v2.5.0 (inactive)
tab-control, v0.6.9 (active)
tron-theme, v0.3.2 (inactive)
turbo-javascript, v1.4.0 (inactive)
typescript-modules-helper, v0.6.2 (active)
v-bootstrap4, v0.1.8 (active)
Visual-Studio-2015-Dark-Theme, v2.3.1 (inactive)
yosemate-ui, v0.7.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (active)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can you check the latest version
