### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mainModule' of undefined

### ISSUE THREAD

**Issue by NadezhdaRay** [skandasoft/open-in-browsers#29]
C:\Users\*\.atom\packages\open-in-browsers\lib\open-in-browsers-view.coffee:78

TypeError: Cannot read property 'mainModule' of undefined
    at OpenInBrowsersView.open (file:///C:/Users/*/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:78:9)
    at OpenInBrowsersView.openBrowser (file:///C:/Users/*/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at HTMLSpanElement.<anonymous> (C:\Users\*\.atom\packages\open-in-browsers\node_modules\space-pen\lib\space-pen.js:220:36)
    at HTMLSpanElement.dispatch (C:\Users\*\.atom\packages\open-in-browsers\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (C:\Users\*\.atom\packages\open-in-browsers\node_modules\jquery\dist\jquery.js:4121:28)

It is happening, when I click 

![screenshot_1](https://cloud.githubusercontent.com/assets/12241762/21215257/1e76a064-c2b1-11e6-9e54-58043d349f21.png)

What should I do?

ATOM v.1.12.7

**Comment by ledsonvanini** [comment]
``<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Assinatura Badran</title>
  </head>
  <body>
    <table style="border: 1px solid black; border-radius:5px; width:50%; height:110px; background-color:gray">
      <tr tablerow="2" style="border: 1px solid black; border-radius:5px; width:600px; height:20px; background-color:red">
        <td></td>
        <td></td>
      </tr>
      <tr style="border: 1px solid black; border-radius:5px; width:600px; height:20px; background-color:blue">
        <td></td>
      </tr>

    </table>

  </body>
</html>

**Comment by donovanash** [comment]
That icon opens Skandasoft's Browser-Plus which gets installed when you install his Browser-Plus Atom package.  You're most likely getting the error because Browser-Plus couldn't be found (not installed).

**Comment by skandasoft** [comment]
check the latest patch
