### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addLeftTile' of undefined

### ISSUE THREAD

**Issue by akradim** [skandasoft/open-in-browsers#31]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.2 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package 0.0.19

### Stack Trace

Uncaught TypeError: Cannot read property 'addLeftTile' of undefined

```
At C:\Users\AKRADIM\.atom\packages\open-in-browsers\lib\open-in-browsers.coffee:236

TypeError: Cannot read property 'addLeftTile' of undefined
    at Object.updateStatusBar (/packages/open-in-browsers/lib/open-in-browsers.coffee:236:31)
    at /packages/open-in-browsers/lib/open-in-browsers.coffee:220:10
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)
    at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)
```

### Commands

```
     -6:42.3.0 core:confirm (input.hidden-input)
  4x -4:58.5.0 core:backspace (input.hidden-input)
  2x -4:55.7.0 core:confirm (input.hidden-input)
     -3:09.0 core:paste (input.hidden-input)
     -2:52 color-picker:open (div.line)
     -2:45.6.0 preview:toggle (div.line.cursor-line)
     -2:26 preview:toggle-options (div.line)
  2x -2:20.3.0 html-to-css:generate (span.syntax--text.syntax--html.syntax--basic)
     -2:07.1.0 tree-view:reveal-active-file (div.line)
     -2:00.8.0 tree-view:show-current-file-in-file-manager (div.line)
     -1:51.9.0 qolor:toggle (div.line)
     -1:43.2.0 python-tools:show-usages (div.line)
 14x -0:59.6.0 core:backspace (input.hidden-input)
     -0:49.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.3 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-monokai-php 1.0.0 
atom-python-run 0.7.2 
atom-python-test 0.5.4 
atom-runner 2.7.1 
atom-terminal 0.8.0 
atom-terminal-panel 4.4.4 
tinacious-design-syntax 1.0.0 
atomic-chrome 0.3.0 
aurora-theme 1.2.2 
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
autocomplete-java 1.2.5 
autocomplete-python 1.8.26 
autocomplete-ruby 0.2.5 
browser-plus 0.0.87 
chester-atom-syntax 0.1.1 
color-picker 2.2.4 
colorblind-wombat-dark-syntax 0.6.0 
file-icons 2.0.9 
file-types 0.5.4-p1 
html-to-css 0.2.2 
icon-fonts 2.11.1 
improved-chester-atom-syntax 0.2.0 
java-class-complete 0.0.6 
java-importer 1.4.1 
linter 1.11.21 
linter-javac 1.9.4 
linter-php 1.3.1 
linter-phpmd 1.5.2 
linter-python 3.0.5 
linter-ruby 1.2.4 
monokai-php-css-syntax 0.2.2 
one-dark-vivid-syntax 1.7.1 
open-html-in-browser 0.1.0 
open-in-browsers 0.0.19 
php-cs-fixer 4.1.0 
php-light-syntax 1.0.2 
preview 0.17.0 
python-autopep8 0.1.3 
python-debugger 0.1.0 
python-indent 1.0.0 
python-tools 0.6.9 
qolor 0.4.1 
ruby-test 1.0.0 
seti-ui 1.4.0 
```

**Comment by skandasoft** [comment]
can you update it to the latest version..
