### ISSUE TITLE
Failed to activate the open-in-browsers package

### ISSUE THREAD

**Issue by 605258778** [skandasoft/open-in-browsers#39]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package 0.0.19

### Stack Trace

Failed to activate the open-in-browsers package

```
At _.contains is not a function

TypeError: _.contains is not a function
    at Function.OpenInBrowsersView.content (/packages/open-in-browsers-master/lib/open-in-browsers-view.coffee:21:13)
    at /packages/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/open-in-browsers-master/lib/open-in-browsers-view.coffee:4:7)
    at Object.activate (/packages/open-in-browsers-master/lib/open-in-browsers.coffee:185:31)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
autocomplete-awk 0.1.2 
node_modules undefined 
open-in-browsers 0.0.19 
```

**Comment by skandasoft** [comment]
```
apm uninstall open-in-browsers 
apm install open-in-browsers

```

else go to the open-in-browsers - package directory and 
```
npm install
```
