### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addSuccess' of undefined

### ISSUE THREAD

**Issue by ediaos** [skandasoft/open-in-browsers#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package, v0.0.7
### Stack Trace

Uncaught TypeError: Cannot read property 'addSuccess' of undefined

```
At /Users/EDiaos/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:40

TypeError: Cannot read property 'addSuccess' of undefined
    at OpenInBrowsersView.module.exports.OpenInBrowsersView.openBrowserPlus (/Users/EDiaos/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:40:24)
    at atom-workspace.<anonymous> (/Users/EDiaos/.atom/packages/open-in-browsers/lib/open-in-browsers.coffee:55:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1016:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:20.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:20.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:17.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:17.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:15.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:15.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:13.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:13.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:10.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:07.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:07.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:02.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:02.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:57.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:24.2.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.7.0 open-in-browsers:BP (span.name.icon.icon-file-text)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.19
atom-sproto-syntax, v0.1.0
autocomplete-paths, v1.0.2
docblockr, v0.7.3
linter, v1.11.3
linter-jshint, v1.2.2
minimap-pigments, v0.1.7
open-in-browsers, v0.0.7

# Dev
No dev packages
```

**Comment by shvargon** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.2
**System**: Ubuntu 14.04.3
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package, v0.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'addSuccess' of undefined

```
At /home/ruande/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:40

TypeError: Cannot read property 'addSuccess' of undefined
    at OpenInBrowsersView.module.exports.OpenInBrowsersView.openBrowserPlus (/home/ruande/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:40:24)
    at HTMLSpanElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLSpanElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:30.1.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  3x -0:27.2.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:26.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:24.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  3x -0:23.3.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  6x -0:16.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:13.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:11 core:move-right (atom-text-editor.editor.is-focused)
     -0:10.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:09.9.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:05.2.0 open-in-browsers:toggle (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {},
  "open-in-browsers": {
    "FireFox": false,
    "IE": false,
    "Opera": false,
    "Safari": false
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.28.22
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-pigments, v0.1.7
open-in-browsers, v0.0.7
pigments, v0.23.1
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
check the latest patch.

**Comment by skandasoft** [comment]
assuming latest patch fixed the issue
