### ISSUE TITLE
Uncaught TypeError: target.closest is not a function

### ISSUE THREAD

**Issue by ouweiya** [skandasoft/open-in-browsers#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package 0.0.22

### Stack Trace

Uncaught TypeError: target.closest is not a function

```
At C:\Users\windows7\.atom\packages\open-in-browsers\lib\open-in-browsers-view.coffee:70

TypeError: target.closest is not a function
    at OpenInBrowsersView.getFilePath (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:70:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:90:14)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:61:8)
    at /packages/open-in-browsers/lib/open-in-browsers.coffee:222:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:07.4.0 open-in-browsers:toggle (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.26 
autocomplete-paths 1.0.5 
browser-plus 0.0.87 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-type-icons 1.3.4 
intentions 1.1.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.2 
linter-ui-default 1.6.0 
livereload 0.4.4 
open-in-browsers 0.0.22 
pigments 0.39.1 
simplified-chinese-menu 5.3.4 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by skandasoft** [comment]
check the latest patch...
