### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new...

### ISSUE THREAD

**Issue by zisheng-ai** [skandasoft/open-in-browsers#48]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0-beta2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [open-in-browsers](https://github.com/skandasoft/open-in-browsers) package 0.0.30

### Stack Trace

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
At C:\Users\10037\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\status-bar\lib\status-bar-view.js:69

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at StatusBarView.module.exports.StatusBarView.addLeftTile (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/node_modules/status-bar/lib/status-bar-view.js:69:28)
    at Object.updateStatusBar (/packages/open-in-browsers/lib/open-in-browsers.coffee:260:32)
    at /packages/open-in-browsers/lib/open-in-browsers.coffee:243:10
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/src/pane-container.js:262:18)
    at Pane.activate (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/src/pane.js:1002:46)
    at Pane.focus (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
     -0:50.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
api-docs 0.0.6 
atom-beautify 0.30.6 
atom-hexo 1.1.1 
atom-ide-ui 0.5.3 
atom-material-ui 2.0.6 
atom-miku 2.2.5 
atom-minify 0.8.0 
atom-ternjs 0.18.3 
autocompiler-pug-jade 2.0.1 
autocomplete-json 5.5.0 
autocomplete-paths 2.12.1 
autoprefixer 3.7.1 
caniuse 0.9.2 
color-picker 2.2.5 
css-snippets 1.1.0 
custom-title 1.0.1 
docblockr 0.12.1 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.13 
flex-tool-bar 0.12.0 
fonts 3.0.3 
git-diff-details 1.4.0 
git-log 0.4.1 
git-status 0.3.4 
git-time-machine 1.5.9 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
hyperlink-hyperclick 1.3.4 
ide-css 0.2.0 
ide-html 0.4.0 
ide-php 0.6.9 
ide-typescript 0.6.2 
insert-timestamp 0.2.4 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-apache 1.7.0 
language-ejs 0.4.0 
language-html-swig 2.0.1 
language-markdown 0.25.1 
language-pug 0.0.21 
language-stylus 0.2.0 
less-autocompile 1.0.0 
linter-eslint 8.4.0 
linter-jshint 3.1.6 
linter-pug 1.3.1 
linter-stylelint 4.0.2 
linter-tidy 2.3.1 
markdown-preview-enhanced 0.14.11 
markdown-table-editor 0.6.4 
markdown-writer 2.7.3 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
one-dark-material-syntax 1.0.3 
open-file 1.4.0 
open-in-browsers 0.0.30 
pdf-view 0.59.0 
php-cs-fixer 4.1.1 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
regex-railroad-diagram 0.19.4 
Remote-FTP 1.2.6 
simple-drag-drop-text 0.3.6 
simplified-chinese-menu 5.3.4 
source-preview 0.5.3 
source-preview-pug 0.2.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.3 
toggle-quotes 1.0.1 
toggler 0.3.0 
tool-bar 1.1.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
wordpress-api 1.2.2 
zip-folder 3.2.0 
```

**Comment by zisheng-ai** [comment]
this package：autocompiler-pug-jade 2.0.1
